oauth:
    client:
        id: test
        secret: 3d2c3e59-af22-400d-8d09-2099aca7001b
    scope: [openid, profile, email]
    device_endpoint: http://172.18.1.5:8080/auth/realms/test/protocol/openid-connect/device/auth
    token_endpoint: http://172.18.1.5:8080/auth/realms/test/protocol/openid-connect/token
    userinfo_endpoint: http://172.18.1.5:8080/auth/realms/test/protocol/openid-connect/userinfo

qr:
    before_line: ""
    after_line: ""
    big: false
    inverse: false

texts:
    prompt: |
        Authenticate at
        -----------------
        {url}
        -----------------
        With code: {code}
        -----------------
        {qr}
        Hit enter when you authenticate
users:
    provider_user_sub_1:
      - machine_username_1
      - machine_username_2
    provider_user_sub_2:
      - machine_username_1
      - machine_username_3